Ignore errors from brew

diff --git a/ci/travis-before_install b/ci/travis-before_install
--- a/ci/travis-before_install
+++ b/ci/travis-before_install
@@ -21,15 +21,24 @@ then
     if [ -n "$BREW_PYTHON" ]
     then
         brew update
-        brew install "$BREW_PYTHON" || brew upgrade "$BREW_PYTHON"
+        if [ "$BREW_PYTHON" = python ]
+        then
+            brew upgrade "$BREW_PYTHON" || echo "Ignoring errors..."
+        else
+            brew install "$BREW_PYTHON" || echo "Ignoring errors..."
+        fi
+        # Ignoring errors above since it may actually be OK to do so.
+        # If install have failed.  `pip --version` will catch that.
+
         if [ "$BREW_PYTHON" = python -a -e /usr/local/bin/pip3 ]
         then
             ln -fs pip3 /usr/local/bin/pip
         fi
+        # https://github.com/tox-dev/tox/blob/master/.travis-osx
+
         which pip
         pip --version
     fi
-    # https://github.com/tox-dev/tox/blob/master/.travis-osx
     # https://docs.brew.sh/Homebrew-and-Python
 
 fi
